export enum Genre {
    Fighting = "Fighting",
    Shooter = "Shooter",
    Music = "Music",
    Platform = "Platform",
    Puzzle = "Puzzle",
    Racing = "Racing",
    RealTimeStrategy = "Real Time Strategy (RTS)",
    RolePlaying = "Role-Playing (RPG)",
    Simulator = "Simulator",
    Sport = "Sport",
    Strategy = "Strategy",
    TurnBasedStrategy = "Turn-based strategy (TBS)",
    Tactical = "Tactical",
    QuizTrivia = "Quiz/Trivia",
    HackSlashBeatEmUp = "Hack and slash/Beat 'em up",
    Pinball = "Pinball",
    Adventure = "Adventure",
    Arcade = "Arcade",
    VisualNovel = "Visual Novel",
    Indie = "Indie",
    CardBoardGame = "Card & Board Game",
    MOBA = "MOBA",
    PointAndClick = "Point-and-click"
  }
